### ISSUE TITLE
bug 从archives页跳转到post页时链接中多了个archieves

### ISSUE THREAD

**Issue by a347807131** [removeif/hexo-theme-icarus-removeif#11]
![image](https://user-images.githubusercontent.com/24996382/75783422-80c61280-5d9b-11ea-85cf-c81b74128718.png)

**Comment by removeif** [comment]
我这边测试没问题，你是怎么跳的？
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200303221709.png)

**Comment by a347807131** [comment]
![image](https://user-images.githubusercontent.com/24996382/75785458-b7e9f300-5d9e-11ea-8b94-8a4b3f696193.png)

![image](https://user-images.githubusercontent.com/24996382/75785531-d94adf00-5d9e-11ea-8137-1203b52ec641.png)
因为跳转链接是相对当前页。

**Comment by a347807131** [comment]
@removeif 
原因找到了，是我博客url填写时来了个/
![image](https://user-images.githubusercontent.com/24996382/75787149-3cd60c00-5da1-11ea-9d15-aec769a8b229.png)
加上后就正常了，但具体原理不清楚。
