### ISSUE TITLE
footer留言跳转页怎么写死了？

### ISSUE THREAD

**Issue by a347807131** [removeif/hexo-theme-icarus-removeif#13]
![image](https://user-images.githubusercontent.com/24996382/75967073-390fca00-5f06-11ea-9714-d38309f97113.png)

我没学过react，就不乱改了。

**Comment by removeif** [comment]
> ![image](https://user-images.githubusercontent.com/24996382/75967073-390fca00-5f06-11ea-9714-d38309f97113.png)
> 
> 我没学过react，就不乱改了。

嗯 这个回头改成相对路径，或者直接去掉

**Comment by a347807131** [comment]
@a347807131 还需要加个config.root，

**Comment by removeif** [comment]
> @a347807131 还需要加个config.root，

嗯，最新代码已经改好了
