### ISSUE TITLE
最新评论设为false关不掉，还有每篇文章为什么评论数显示为99+，大佬能帮忙么

### ISSUE THREAD

**Issue by lmlmkp** [removeif/hexo-theme-icarus-removeif#15]

**Comment by removeif** [comment]
最新评论在 独立的主题最新代码中 修复了 请查看 https://github.com/removeif/hexo-theme-amazing
每篇文章为什么评论数 显示 99+是因为没有初始化 文章的评论，需要点下，文章下面的评论中的初始化

**Comment by lmlmkp** [comment]
> 最新评论在 独立的主题最新代码中 修复了 请查看 https://github.com/removeif/hexo-theme-amazing
> 每篇文章为什么评论数 显示 99+是因为没有初始化 文章的评论，需要点下，文章下面的评论中的初始化

我初始化了也换号评论了一下，还是和其他没初始化或的文章一样99+

**Comment by removeif** [comment]
> > 最新评论在 独立的主题最新代码中 修复了 请查看 https://github.com/removeif/hexo-theme-amazing
> > 每篇文章为什么评论数 显示 99+是因为没有初始化 文章的评论，需要点下，文章下面的评论中的初始化
> 
> 我初始化了也换号评论了一下，还是和其他没初始化或的文章一样99+

那不会吧，网址在啥，发来我看看

**Comment by lmlmkp** [comment]
> > > 最新评论在 独立的主题最新代码中 修复了 请查看 https://github.com/removeif/hexo-theme-amazing
> > > 每篇文章为什么评论数 显示 99+是因为没有初始化 文章的评论，需要点下，文章下面的评论中的初始化
> > 
> > 
> > 我初始化了也换号评论了一下，还是和其他没初始化或的文章一样99+
> 
> 那不会吧，网址在啥，发来我看看

弄好了，谢谢大佬，我那个配置地址后忘加/issues了
