### ISSUE TITLE
暗黑模式触发问题

### ISSUE THREAD

**Issue by NavePnow** [removeif/hexo-theme-icarus-removeif#5]
您好，我按照你的commit记录，在我的 icarus 里面进行对应的修改，hexo server是可以触发暗黑模式的，但 hexo g -d 之后部署到网页版就不行了，不知道为什么。
谢谢

**Comment by removeif** [comment]
> 您好，我按照你的commit记录，在我的 icarus 里面进行对应的修改，hexo server是可以触发暗黑模式的，但 hexo g -d 之后部署到网页版就不行了，不知道为什么。
> 谢谢

我看可以呢
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2019/20191123101656.png)

**Comment by NavePnow** [comment]
哇，昨晚部署了一下不行的嘞，今早上先clean了一下，就可以了嘿嘿，谢啦
