### ISSUE TITLE
引入Echarts时在文章首页可以看的到，点阅读更多进去后就看不到了，大佬能帮我看看吗

### ISSUE THREAD

**Issue by FuShaoLei** [removeif/hexo-theme-icarus-removeif#7]
出问题的博客文章：https://fushaolei.github.io/2020/02/06/Java-Java%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/
博客源码地址：https://github.com/FuShaoLei/FuShaoLei.github.io/tree/hexo/Hexo
很奇怪的问题，不知道什么原因

**Comment by removeif** [comment]
> 出问题的博客文章：https://fushaolei.github.io/2020/02/06/Java-Java%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/
> 博客源码地址：https://github.com/FuShaoLei/FuShaoLei.github.io/tree/hexo/Hexo
> 很奇怪的问题，不知道什么原因

你的引入路径不对
![](https://cdn.jsdelivr.net/gh/removeif/blog_image/img/2020/20200208163648.png)
写成这样
/js/.....js
不要前面的. 试试呢

**Comment by removeif** [comment]
@FuShaoLei

**Comment by FuShaoLei** [comment]
好了😱居然是这种问题 谢谢大佬😊
